doc/toc.yml
doc/uno-resizetizer-properties.md
src/Resizetizer/src/ResizeImageInfo.cs
src/Resizetizer/src/ResizetizeImages.cs

GitHub Issue (If applicable): #109
This PR adds the ability to add the ForegroundScale per platform

Apply ForegroundScale per platform

---

src/Resizetizer/Directory.UnoMetadata.targets
src/Resizetizer/src/Resizetizer.csproj

- Feature
Package meta data in csproj
Meta data (including icon downloader) in targets file

feat: Adding metadata targets file

---

src/.nuspec/Uno.Resizetizer.targets

fix: Create `IntermediateOutputPath` first if it doesn't exist

---

samples/NewTemplate/Resizetizer.Extensions.Sample.Base/AppHead.xaml.cs
src/.nuspec/Uno.Resizetizer.targets

- closes #129
- Bugfix
Windows head does not have code generated for the Window Icon Extensions
The target now ensures it runs before XamlPreCompile and it exists early enough for the compilation to succeed.

Fix Window Icon Extensions

---

src/.nuspec/Uno.Resizetizer.targets

This PR is a port of a fix implemented on #134 ticket.
On the new template, if you rebuild the class lib project and press F5 or just build the head project, the `Pwa manifest` will not be updated nor the `ApplicationIcon`(for Skia targets). The reason is that the `ResizetizerImages_v0` task will not be executed since the Inputs/Outputs will be evaluated as the same as the previous build.
This PR adds a step to lookup the generated files and find the `Pwa manifest` and `Application icon` and include them in the build process.

Fixed incremental builds

---

src/.nuspec/Uno.Resizetizer.targets

- n/a
- Bugfix
Properties used by Resizetizer all start Resizetize/Resizetizer
Properties are now prefixed with Uno to ensure proper separation.

Rename all properties so that they are prefixed with Uno

---

doc/using-uno-resizetizer.md

On our docs the last tab can't be selected, that could be caused by some bad formatting on our end. So, in order to fix that I changed the `tab end` symbol to match what MS uses for Xamarin.Essentials docs. Since we use the same engine.

Changed the tab end symbol

---

src/.nuspec/Uno.Resizetizer.targets

This is to avoid another naming colision

Renamed another target name

---

samples/NewTemplate/Resizetizer.Extensions.Sample.sln
src/.nuspec/Uno.Resizetizer.android.targets
src/.nuspec/Uno.Resizetizer.apple.targets
src/.nuspec/Uno.Resizetizer.targets
src/.nuspec/Uno.Resizetizer.wasm.targets
src/.nuspec/Uno.Resizetizer.windows.skia.targets

This PR brings back the idea to refactor the platform code into separate files in order to make it easier to maintain. All the samples are running just like the `main` branch, so this doesn't change any behavior of the Resizetizer.
Closes: #134

Refactoring the MSBuild tasks

---

src/.nuspec/Uno.Resizetizer.targets

Fixes: Canary build error on templates
- Bugfix
WinUI detection not working meaning that WindowsIcon code not being generated
WinUI detection working so WindowsIcon code is generated

fix: Testing for winuitools

---

src/.nuspec/Uno.Resizetizer.targets

- Bugfix
Adds the ability to disable the generated windows extensions. Used when building with UWP inside the uno solution.

fix: Add the ability to disable Windows extensions generation

---

src/.nuspec/Uno.Resizetizer.targets
src/Resizetizer/src/GenerateWasmSplashAssets.cs
src/Resizetizer/src/ResizeImageInfo.cs
src/Resizetizer/src/ResizetizeImages.cs
src/Resizetizer/test/UnitTests/ResizetizeImagesTests.cs

Fixes: #156 
- Bugfix
The icon background wasn't tinted with the backgroundColor set on `UnoSplashScreen`.
The icon's background is tinted with the color set on `UnoSplashScreen`.

Set the correct background color on SplashScreen's background

---

.github/workflows/ci.yml

So, you may notice that we decore some `MSBuild` tasks with the `v_0` suffix, this is intended to be changed, during the build, to the commit hash, in order to avoid confusion with different Uno.Resizetizer packages in the nuget cache. This appears in the first place when you have the `Uno.Resizetizer 1.2.0-dev.39`  and update to `1.2.0-dev.76`, will break the build, because there's a breaking change on the task, and the compiler will try to use the old version.
The issue was that our CI was using the wrong variable to replace the `v_0` and now using the correct one should fix it and make the world happy again. The good news is the git keeps generating different hashes for commits, so no apocalypse so far.

[🔥HotFix] Fixed the git hash used

---

doc/uno-resizetizer-properties.md
samples/NewTemplate/Resizetizer.Extensions.Sample.Base/base.props
src/Resizetizer/src/ResizeImageInfo.cs
src/Resizetizer/src/Resizer.cs

Fixes: #188
Before / After
- Feature

Allow to apply Scale on UnoSplashScreen

---

src/.nuspec/Uno.Resizetizer.targets

This issue was reported by @agneszitte on teams.
If there's no UnoSplashScreen and UnoIcon, the validation will say that `UnoIcon == UnoSplashScreen` and we that validation shouldn't run if one of those are empty.
@agneszitte can you try the generated package and confirm if it fixes the issue?

Fixed validation logic to check if UnoSplashScreen == UnoIcon

---

samples/NewTemplate/Resizetizer.Extensions.Sample.Skia.Gtk/Resizetizer.Extensions.Sample.Skia.Gtk.csproj
samples/NewTemplate/Resizetizer.Extensions.Sample.Skia.WPF/Resizetizer.Extensions.Sample.Skia.WPF.csproj
src/.nuspec/Uno.Resizetizer.windows.skia.targets
src/Resizetizer/src/DpiPath.cs

Fixes: #199
From the original implementation, Skia Targets generates just one icon image, in terms of usability that was enough, but since Skia Targets uses the `appxmanifest` this PR updates those targets to generate the same assets as winUI and match with the generated `appxmanifest`.

Fix the appxmanifest generation

---

src/.nuspec/Uno.Resizetizer.targets
src/.nuspec/Uno.Resizetizer.windows.skia.targets
src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/src/WindowIconGeneratorTask.cs

Fixes: #208 
Replaces #209 
- Bugfix
On Windows targets, `AppWindow` currently lacks a default value for its `Title` property. 
In our task for generating window icon, we form the code to retrieve an `AppWindow` from the XAML `Window`, using it to conveniently set the generated `ico` file. 
Upon retrieval of `AppWindow`, set AppWindow.Title to be the app's `DisplayName`. This value is obtained from the XAML `Window` instance which has a pre-defined `Title` property. (defaulting to `DisplayName`)
Internal Issue (If applicable): N/A

fix: Set AppWindow.Title to DisplayName

---

src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/test/UnitTests/GeneratePackageAppxManifestTests.cs
src/Resizetizer/test/UnitTests/Resizetizer.UnitTests.csproj

Change the TaskItem on GenerateAppxManifestFile to be a collection

---

src/Resizetizer/src/Resizetizer.csproj

Fixes: #
- fixes #222
- Bugfix
Native libraries are not being properly loaded from the packaged NuGet
Native libraries drop the host os for the assets. This reverts to the same sort of behavior we had explicitly in the past while maintaining a more dynamic approach that will automatically grab assets for us.

Fixing output directory for Runtime Assets

---

samples/Directory.Build.targets
samples/nuget.config
src/.nuspec/Uno.Resizetizer.targets
src/Resizetizer/src/Resizetizer.csproj

Fixes: #
- fixes #225
- fixes canaries
- Bugfix
We rely on the runtime to resolve the correct runtime assets
We build the sample against locally built binaries
HACK: We have added a task to move the correct runtime assets to the executing directory for Resizetizer.
We build the sample against the generated NuGet package

Updates Sample to build against generated NuGet

---

src/.nuspec/Uno.Resizetizer.targets

Fixes a race condition found when building in cross targeted projects, where the runtime target may fail to detect a concurrent runtime copy

fix: Adjust targets for runtime workaround

---

src/.nuspec/Uno.Resizetizer.android.targets
src/.nuspec/Uno.Resizetizer.targets

This avoids  GenerateUnoSplashAndroid to run even if GenerateUnoSplashScreens was ignore for input/output rules, later causing Aapt2Compile to run on removed files.
Fixes https://github.com/unoplatform/uno.resizetizer/issues/232

fix: Aligns input/outputs of GenerateUnoSplashAndroid with GenerateUnoSplashScreens

---

src/.nuspec/Uno.Resizetizer.android.targets
src/.nuspec/Uno.Resizetizer.apple.targets
src/.nuspec/Uno.Resizetizer.targets
src/.nuspec/Uno.Resizetizer.wasm.targets

The v0 suffix should be present only on Tasks
Fixes: #

[♻️ Housekepping] Remove v0 suffix from Target names

---

samples/5.2/Uno52ResizetizerTests/Uno52ResizetizerTests/Package.appxmanifest
src/.nuspec/Uno.Resizetizer.windows.skia.targets
src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/test/UnitTests/GeneratePackageAppxManifestTests.cs
src/Resizetizer/test/UnitTests/testdata/appxmanifest/typical.appxmanifest
src/Resizetizer/test/UnitTests/testdata/appxmanifest/typicalWithNoBackground.appxmanifest

Fixes: #
- fixes #272
- Bugfix
Properties like the Application Title and Version numbers are not correctly applied. 
Refactors the execution logic to simplify away from heavily nested if statements.
This now correctly applies the Application Title, and other common Single Project MSBuild properties.

Fix appxmanifest merge

---

src/.nuspec/Uno.Resizetizer.targets
src/Resizetizer/src/WindowIconGeneratorTask.cs

Fixes: #
- closes #267
- Bugfix
The Window title is always set on Windows
The Window title is ONLY set on Windows when Unpackaged and if the Window title has the default `WinUI Desktop` value.

Update Window Title logic

---

src/.nuspec/Uno.Resizetizer.targets

Fixes: #
- fixes #277 
- Bugfix
Resizetizer uses the NETCoreSdkRuntimeIdentifier to identify the proper Runtime assets to load
We sanitize the Runtime Identifier when working with a non-standard Identifier like `ubuntu.22.04-x64`

Linux runtimes

---

doc/using-uno-resizetizer.md

Fixes: #
- Documentation content changes
Updated docs with single project usages, Platform-specific customization and SVG vs PNG Image use( #260 , #261 , [#15869](https://github.com/unoplatform/uno/issues/15869) )

docs: adding single project usages + Platform-specific customization + SVG vs PNG Image use

---

doc/using-uno-resizetizer.md

related issue: #289 
- Documentation content changes

docs: add icon troubleshooting

---

src/Resizetizer/src/AppleIconAssetsGenerator.cs
src/Resizetizer/src/DpiPath.cs
src/Resizetizer/src/Resizer.cs
src/Resizetizer/src/ResizetizeImages.cs
src/Resizetizer/src/Resizetizer.csproj
src/Resizetizer/test/UnitTests/ResizetizeImagesTests.cs

Fixes: #
- fixes #301
- Feature
When generating the App Icon for the Desktop target on MacOS we continue to generate the Windows/WPF app icons
When generating the App Icon for the Desktop target on MacOS we now intercept this and generate an AppIconSet that can be properly used when we package the application.

Generate AppIconSet for Desktop on MacOS

---

samples/Legacy/Uno.Resizetizer.Sample/Uno.Resizetizer.Sample.Wasm/Uno.Resizetizer.Sample.Wasm.csproj
samples/NewTemplate/Resizetizer.Extensions.Sample.Wasm/Resizetizer.Extensions.Sample.Wasm.csproj
src/.nuspec/Uno.Resizetizer.targets
src/.nuspec/Uno.Resizetizer.wasm.targets
src/Resizetizer/src/ResizetizeImages.cs
src/Resizetizer/src/WasmIconGenerator.cs

fix: Override WasmPWAManifestFile properly

---

.github/workflows/ci.yml
src/Resizetizer/src/SkiaSharpTools.Initializer.cs

fixes #315, closes https://github.com/unoplatform/uno/issues/18211

fix: Adjust VS build

---

doc/using-uno-resizetizer.md

Corrected some samples and added missed information
Fixes: #

docs: Update SVG directions

---

src/Resizetizer/src/WindowIconGeneratorTask.cs

Fixes: #309 
- Bugfix
WinUI Window title shows "WinUI Dekstop"
Set the correct Window title regardless of whether it is Packaged or not.

fix: WinUI Packaged Window Title

---

src/Resizetizer/src/AndroidAdaptiveIconGenerator.cs
src/Resizetizer/src/AppleIconAssetsGenerator.cs
src/Resizetizer/src/ResizetizeImages.cs
src/Resizetizer/src/Utils.cs
src/Resizetizer/test/UnitTests/ResizetizeImagesTests.cs

fix: icons generation frequency

---

version.json

This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/1.8, based on #336

Version bump after 1.8 release branch

---

version.json

This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/1.9, based on #339

Version bump after 1.9 release branch

---

version.json

- Build or CI related changes
Move to dotnet-sign and not use the legacy signing service anymore
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/1.10, based on #350

Version bump after 1.10 release branch
