unoplatform/uno.resizetizer

.github/workflows/ci.yml
src/.nuspec/Uno.Resizetizer.targets
src/Resizetizer/src/ResizetizeImages.cs
src/Resizetizer/test/UnitTests/ResizetizeImagesTests.cs
src/Resizetizer/uno.resizetizer.sln

Adjust XA0101, add samples test

---

src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/src/GenerateWasmSplashAssets.cs
src/Resizetizer/src/Utils.cs
src/Resizetizer/test/UnitTests/GeneratePackageAppxManifestTests.cs
src/Resizetizer/test/UnitTests/testdata/appxmanifest/typicalWithNoBackground.appxmanifest

Added background color on appxmanifest and refactoring.

---

src/.nuspec/Uno.Resizetizer.targets

Fix assets not being copied/generated at first build

---

samples/NewTemplate/Resizetizer.Extensions.Sample.Windows/Resizetizer.Extensions.Sample.Windows.csproj
src/Resizetizer/src/DpiPath.cs
src/Resizetizer/test/UnitTests/GenerateSplashAssetsTests.cs
src/Resizetizer/test/UnitTests/testdata/appxmanifest/typical.appxmanifest
src/Resizetizer/test/UnitTests/testdata/appxmanifest/typicalWithNoBackground.appxmanifest

Normalize appxmanifest and splash generation

---

src/Resizetizer/src/GenerateSplashAndroidResources.cs
src/Resizetizer/test/UnitTests/GenerateSplashAndroidResourcesTests.cs

[Android] set transparent as default background color

---

src/Resizetizer/src/ResizeImageInfo.cs

Fixes: #96 
Solution was inspired by : https://github.com/dotnet/maui/pull/11965

Make sure all cultures works

---

doc/using-uno-resizetizer.md

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/11968

Fixed splash screen docs

---

src/.nuspec/Uno.Resizetizer.targets

This will avoid some name colisions

Changed the property related to the Uno.Resizetizer task dll

---

samples/NewTemplate/Resizetizer.Extensions.Sample.Windows/Resizetizer.Extensions.Sample.Windows.csproj
src/.nuspec/Uno.Resizetizer.targets

GitHub Issue (If applicable): #119

Ignore Link property on UnoIcon/SplashScreen

---

src/Resizetizer/src/GenerateWasmSplashAssets.cs

Changed the splash scale to be used on wasm

---

doc/using-uno-resizetizer.md

- Documentation content changes
Fixed readability

docs: Update using-uno-resizetizer.md

---

src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/test/UnitTests/GeneratePackageAppxManifestTests.cs
src/Resizetizer/test/UnitTests/testdata/appxmanifest/typical.appxmanifest
src/Resizetizer/test/UnitTests/testdata/appxmanifest/typicalWithNoBackground.appxmanifest

Fixed BackgroundColor on SplashScreen winUI

---

src/Resizetizer/src/WindowIconGeneratorTask.cs

GitHub Issue (If applicable): #149 
- Bugfix
No comment on WindowExtension generated class
Generated class has comment

fix: Adding comment to generated WindowExtensions class

---

src/.nuspec/Uno.Resizetizer.targets

Normalize with Uno prefix and _v0 on task names

---

gitversion.yml
samples/Legacy/Uno.Resizetizer.Sample/Uno.Resizetizer.Sample.Mobile/Uno.Resizetizer.Sample.Mobile.csproj
samples/Legacy/Uno.Resizetizer.Sample/Uno.Resizetizer.Sample.Skia.Gtk/Uno.Resizetizer.Sample.Skia.Gtk.csproj
samples/Legacy/Uno.Resizetizer.Sample/Uno.Resizetizer.Sample.Skia.Linux.FrameBuffer/Uno.Resizetizer.Sample.Skia.Linux.FrameBuffer.csproj
samples/Legacy/Uno.Resizetizer.Sample/Uno.Resizetizer.Sample.Skia.Wpf/Uno.Resizetizer.Sample.Skia.Wpf.csproj
samples/Legacy/Uno.Resizetizer.Sample/Uno.Resizetizer.Sample.Wasm/Uno.Resizetizer.Sample.Wasm.csproj
samples/Legacy/Uno.Resizetizer.Sample/Uno.Resizetizer.Sample.Windows/Uno.Resizetizer.Sample.Windows.csproj
samples/NewTemplate/Directory.Packages.props
samples/NewTemplate/Resizetizer.Extensions.Sample.Skia.Gtk/Program.cs
src/Resizetizer/Directory.build.props
src/Resizetizer/src/ResizetizerPackages.projitems
src/Resizetizer/test/UnitTests/Resizetizer.UnitTests.csproj

chore: Bump to 5

---

.gitignore
src/Resizetizer/src/Resizetizer.csproj

GitHub Issue (If applicable): #160 
- Bugfix
The nuget didn't have the platform target files.
The nuget has the platform target files (I hope)

🔥 Hot fix - added platoform targets during the pack

---

.github/pull_request_template.md

THis is just a housekeeping PR, now when we reference an issue on PR it will be linked.

chore: update PR template to link issue

---

src/Resizetizer/Directory.build.props

♻️ bump packages versions

---

src/.nuspec/Uno.Resizetizer.android.targets
src/.nuspec/Uno.Resizetizer.apple.targets
src/.nuspec/Uno.Resizetizer.windows.skia.targets

Fixes: #178 
This PR adds a missing verification on target platforms, to not run the Splash task if there's no `UnoSplashScreen` defined on the project.
App crashes and devs are sad.
App runs and everyone is happy

Add validation to check if there's UnoSplashScreen

---

src/Resizetizer/src/ResizetizerPackages.projitems

Fixes: #184 
Adding the reference of `System.Text.Encondings.Web` to make sure it will be picked during the build. Looks like the env. can influence the version that Resizetizer will use and it causes the error of not finding the method. Let's hope this is the last one. This theory is based on the fact that the sample project builds on both VS and terminal, but when the nuget is referenced, external projects fail.

Added System.Text.Encondings.Web explicitly

---

doc/using-uno-resizetizer.md
samples/NewTemplate/Resizetizer.Extensions.Sample.Wasm/manifest.json
src/Resizetizer/src/CreatePartialInfoPlistTask.cs
src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/src/GenerateSplashAndroidResources.cs
src/Resizetizer/src/GenerateSplashAssets.cs
src/Resizetizer/src/GenerateSplashStoryboard.cs
src/Resizetizer/src/GenerateWasmSplashAssets.cs
src/Resizetizer/src/JsonHelper.cs
src/Resizetizer/src/ResizetizeImages.cs
src/Resizetizer/src/WasmIconGenerator.cs

Fixes: #191
- Feature
Now users can have comments on their `pwa.manifest`, it will be ignored during the parsing, but the build will not fail.

Allow comments on json document

---

src/.nuspec/Uno.Resizetizer.targets

Fixes: #
updates new TFMs
- Bugfix
- Feature
checks for `-browser` and `-skia`
checks for `-browserwasm` and `-desktop`

Update for new tfms

---

.gitignore
src/.nuspec/Uno.Resizetizer.targets

Fixes https://github.com/unoplatform/uno.resizetizer/issues/230

fix: Ensure native assets init is run on windows

---

src/.nuspec/Uno.Resizetizer.android.targets

Apply the same technique found in https://github.com/unoplatform/uno/pull/14302
Fixes https://github.com/unoplatform/uno.resizetizer/issues/232

fix: Adjust android incremental builds

---

src/.nuspec/Uno.Resizetizer.wasm.targets

those inputs are used by other targets, so it will mess things up
Fixes: #240

Remove inputs on GenerateUnoSplashWasm target

---

doc/using-uno-resizetizer.md

#206
- Documentation content changes

docs: Add UWP not supported note

---

src/.nuspec/Uno.Resizetizer.targets

Make sure VS doesn't messup with Splash-screen generation

---

src/.nuspec/Uno.Resizetizer.android.targets
src/.nuspec/Uno.Resizetizer.apple.targets
src/.nuspec/Uno.Resizetizer.windows.skia.targets

Fixes: #244
Looking into binlog attached to the issue, I could see the cause of this error was a skipping target for `GenerateSplash`, and I fixed that for wasm on #241, so my guess is that we should remove all these Inputs from other targets as well. That should fix everything and missed during our refactoring, since VS behaves in a very unpredictable way.

Remove inputs from all GenerateSplash Targets

---

samples/NewTemplate/Resizetizer.Extensions.Sample/Assets/Icons/back.svg

Fixes: #
- closes #275 
- Build or CI related changes
Build is failing
Regression tests should not fail

Regression testing fix

---

src/Resizetizer/src/CreatePartialInfoPlistTask.cs
src/Resizetizer/src/FileHelper.cs
src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/src/GenerateSplashStoryboard.cs
src/Resizetizer/src/GenerateWasmSplashAssets.cs

Fixes: https://github.com/unoplatform/uno.resizetizer/issues/282

fix(incremental): Don't write files that have not changed

---

src/Resizetizer/src/FileHelper.cs
src/Resizetizer/src/GeneratePackageAppxManifest.cs
src/Resizetizer/test/UnitTests/GeneratePackageAppxManifestTests.cs
src/Resizetizer/test/UnitTests/testdata/appxmanifest/duplicate-versions.expected.appxmanifest
src/Resizetizer/test/UnitTests/testdata/appxmanifest/duplicate-versions.input.appxmanifest

Fixes: #
- fixes #287 
- fixes #292
- Bugfix
We just rely on File.Move
If the file currently exists we will first delete the existing one.

Ensure that we can overwrite existing files.

---

doc/using-uno-resizetizer.md

https://github.com/unoplatform/private/issues/504

docs: Update appxmanifest link

---

.github/workflows/ci.yml
src/.nuspec/Uno.Resizetizer.targets
src/Resizetizer/src/SkiaSharpTools.Initializer.cs
src/Resizetizer/src/SkiaSharpTools.cs

fixes https://github.com/unoplatform/uno/issues/17897
This PR avoids nuget-cache file copy to match the current runtime and underlying platform, and loads skiasharp in place.

Adjust SkiaSharp loading

---

src/Resizetizer/src/WindowIconGeneratorTask.cs

feat: Avoid startup exception for WinAppSDK Unpackaged apps

---

src/Resizetizer/test/UnitTests/Resizetizer.UnitTests.csproj

chore: target tests to .net8.0

---

src/Resizetizer/src/Resizetizer.csproj

Fixes: #
- Other... Please describe:
Updates vulnerabilities: https://github.com/unoplatform/uno.resizetizer/security/dependabot/4

chore: update dependencies with vulnerability

---

src/Resizetizer/src/AppleIconAssetsGenerator.cs
src/Resizetizer/src/DpiPath.cs
src/Resizetizer/src/ResizetizeImages.cs
src/Resizetizer/test/UnitTests/MSBuildTaskFixture.cs

Fixes: https://github.com/unoplatform/uno-private/issues/1443
- Bugfix

fix: avoid null pointer building sample solution

---

src/Resizetizer/Resizetizer.Generators/WindowTitleGenerator.cs

Fixes: https://github.com/unoplatform/uno.resizetizer/issues/347
- Bugfix

 fix: create extension method for net9.0 target

---

version.json

Fixes: https://github.com/unoplatform/uno.resizetizer/issues/347
- Bugfix
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/1.11, based on #355

Version bump after 1.11 release branch
